env:
  matrix:
    - MYCONDAPY=2.7
    - MYCONDAPY=3.7
  global:
    # ANACONDA_TOKEN
    - secure: "C9W6W6tPzXEhMWpkrRSf3lx6f3JJ5j5jZCsGymUQqrF9SU7RLgTvINc57M72s+I9enaL8wvldELzut0pamzMxuicFeFsSZzPlBuPdJcAy1QdxDYI3HWM8g/TmLTq9PV9sBgmbJ7rO7hGYdAXcTcrfFQk3SBARUWF5IGA95k+Kto="
    # GITHUB_TOKEN
    - secure: "Skwu+NVG5NuZdp6G8N4y4dPS4nGmifg2NSgp/Vz2vUO0R34IrdY/lBT0aWoDMVxxYnG6h8U0S4mr3NKgVvcbugXD/omDDLJlg07PmpByrZI42gSpRcnQ6CVq8teEwCFT923ZaM5T+jujTHHQ3fzP219J/Jy+WxyImUjDVTxIzBQ="
    # PYPI_PASSWD
    - secure: "K3A2uBMjw2akoLaVeKMkW7kpxsui5yz9GClUjWgP2L/hbt9S4S81fwE+8htw2gDmM1ehFDhWgbHYU1HomB3k6KHhaBxmtyZ842dewqZRgtdwKQUyVleK0FaB+I1MpJyVggABfAbwSuqCDaL2QxDVnDmwdJ45yed4DPemyuCMkEw="
    - PYPKG=tamkin
    - GITHUB_REPO_NAME=molmod/tamkin

# Do not use Travis Python to save some time.
language: generic
dist: xenial

branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+(\.[0-9]+)?([ab][0-9]+)?$/

install:
# Get miniconda. Take the right version, so re-installing python is only needed for 3.5.
- if [[ "$MYCONDAPY" == "2.7" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  fi
- bash miniconda.sh -b -p $HOME/miniconda
- source ~/miniconda/bin/activate
- hash -r

# Configure conda and get a few essentials
- conda config --set always_yes yes
# The following line is needed to override Travis' setuptools, which
# seems to confuse conda.
- conda install setuptools
- conda update conda
# Get the right python version for building. This only does something for 3.5.
# Install extra package needed to make things work. Most things can be listed as
# dependencies on metal.yaml and setup.py, unless setup.py already imports them.
# Install conda tools for packaging and uploading
- conda install python=${MYCONDAPY} sphinx conda-build anaconda-client numpy codecov coverage nose graphviz conda-verify
# Add the molmod channel to get access to the molmod dependency
- conda config --add channels molmod
# Show conda info for debugging
- conda info -a

# No visual backend for matplotlib
- mkdir -p ~/.config/matplotlib/
- echo backend:agg > ~/.config/matplotlib/matplotlibrc

script:
# Check if code is normalized properly, whitespace etc
- wget https://raw.githubusercontent.com/tovrstra/devscripts/master/scripts/ds-normalize-code -O ds-normalize-code;
  chmod +x ds-normalize-code;
  ./ds-normalize-code;

# Build the conda package
- git fetch origin --tags
- conda build tools/conda.recipe

# Build source package, should work too and needed for deployment.
- python setup.py sdist

# Install Conda package
- conda install --use-local $PYPKG

# Compile documentation
- (cd doc; make html)

# Run tests out of source tree, to make sure that installed version is tested.
- (cd; nosetests $PYPKG -v --detailed-errors --with-coverage --cover-package=$PYPKG --cover-tests --cover-erase --cover-inclusive --cover-branches --cover-xml)

after_success:
# Upload the coverage analysis
- codecov -f ~/coverage.xml

# In deployment, the env var TRAVIS_TAG contains the name of the current tag, if any.
deploy:
- provider: releases
  skip_cleanup: true
  token: ${GITHUB_TOKEN}
  file: dist/${PYPKG}-${TRAVIS_TAG}.tar.gz
  on:
    repo: ${GITHUB_REPO_NAME}
    tags: true
    condition: "$TRAVIS_TAG != *[ab]* && $MYCONDAPY == 2.7 && $TRAVIS_OS_NAME == linux"
  prerelease: false
- provider: releases
  skip_cleanup: true
  token: ${GITHUB_TOKEN}
  file: dist/${PYPKG}-${TRAVIS_TAG}.tar.gz
  on:
    repo: ${GITHUB_REPO_NAME}
    tags: true
    condition: "$TRAVIS_TAG == *[ab]* && $MYCONDAPY == 2.7 && $TRAVIS_OS_NAME == linux"
  prerelease: true
- provider: script
  skip_cleanup: true
  script: anaconda -t $ANACONDA_TOKEN upload --force -l alpha ${HOME}/miniconda/conda-bld/*/${PYPKG}-*.tar.bz2
  on:
    repo: ${GITHUB_REPO_NAME}
    tags: true
    condition: "$TRAVIS_TAG == *a*"
- provider: script
  skip_cleanup: true
  script: anaconda -t $ANACONDA_TOKEN upload --force -l  ${HOME}/miniconda/conda-bld/*/${PYPKG}-*.tar.bz2
  on:
    repo: ${GITHUB_REPO_NAME}
    tags: true
    condition: "$TRAVIS_TAG == *b*"
- provider: script
  skip_cleanup: true
  script: anaconda -t $ANACONDA_TOKEN upload --force -l main ${HOME}/miniconda/conda-bld/*/${PYPKG}-*.tar.bz2
  on:
    repo: ${GITHUB_REPO_NAME}
    tags: true
    condition: "$TRAVIS_TAG != *[ab]*"
- provider: pypi
  skip_cleanup: true
  user: molmod
  password: ${PYPI_PASSWD}
  on:
    repo: ${GITHUB_REPO_NAME}
    tags: true
    condition: "$TRAVIS_TAG != *[ab]* && $MYCONDAPY == 2.7 && $TRAVIS_OS_NAME == linux"
- provider: pages
  skip_cleanup: true
  token: ${GITHUB_TOKEN}
  project_name: ${PYPKG}
  local_dir: doc/_build/html
  on:
    repo: ${GITHUB_REPO_NAME}
    condition: "$TRAVIS_TAG != *[ab]* && $MYCONDAPY == 2.7 && $TRAVIS_OS_NAME == linux"
    tags: true
